# deploy weight 50

# use existing t2_proxy network defined by docker-env stack
networks:
  t2_proxy:
    name: t2_proxy
    external: true
    
services:
  vscode-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:4.104.2@sha256:f0f4cc06a8c642e61299fe57b01fe2d5ded3934e923aba7456770e70a3c8cf97
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=svcode.$DOMAINNAME_CLOUD_SERVER #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - $VOLUME_DIR/vscode-server/config:/config
      - $VOLUME_DIR:/volumes
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.vscode-rtr.entrypoints=https"
      - "traefik.http.routers.vscode-rtr.priority=1"
      - "traefik.http.routers.vscode-rtr.rule=Host(`vscode.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.vscode-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.vscode-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.vscode-rtr.service=vscode-svc"
      - "traefik.http.services.vscode-svc.loadbalancer.server.port=8443"
