# deploy weight 50

# use existing t2_proxy network defined by docker-env stack
networks:
  t2_proxy:
    name: t2_proxy
    external: true
    
services:
  vscode-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:4.96.2@sha256:c181b7a2ae59940f276c89fd86cd4f220cdb87886d771b5becf3d4156b3c0bc1
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=svcode.$DOMAINNAME_CLOUD_SERVER #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - $VOLUME_DIR/vscode-server/config:/config
      - $VOLUME_DIR/../github:/github/homeserver-docker:ro
      - $VOLUME_DIR:/volumes
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.vscode-rtr.entrypoints=https"
      - "traefik.http.routers.vscode-rtr.priority=1"
      - "traefik.http.routers.vscode-rtr.rule=Host(`vscode.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.vscode-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.vscode-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.vscode-rtr.service=vscode-svc"
      - "traefik.http.services.vscode-svc.loadbalancer.server.port=8443"
