# deploy weight 70

networks:
  # TODO: move to own isolated network
  abs_green_internal:
    name: abs_green_internal
    external: true

services:
  fittools:
    container_name: fittools
    image: ghcr.io/jacobfg/garmin-fit-scripts:latest@sha256:170e94120c891a4c532d16a146a5efc1bcab12792d6f852f9f547d390430b2bd
    restart: unless-stopped
    user: $PUID:$PGID
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256M
    environment:
      - TZ=$TZ
    networks:
      - abs_green_internal
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.fittools-rtr.entrypoints=https"
      - "traefik.http.routers.fittools-rtr.rule=Host(`fittools.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.fittools-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.fittools-rtr.middlewares=middlewares-homer-cors@file,chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.fittools-rtr.service=fittools-svc"
      - "traefik.http.services.fittools-svc.loadbalancer.server.port=8080"
