# deploy weight 49

# use existing t2_proxy network defined by docker-env stack
networks:
  t2_proxy:
    name: t2_proxy
    external: true

services:
  libation:
    container_name: libation
    image: rmcrackan/libation:14.2.0@sha256:c0ab061d317621057e914c51506d57238d5b6afb158c4aa5801b2fa29b15d8db
    restart: unless-stopped
    user: $PUID:$PGID
    environment:
      - TZ
      - LIBATION_DB_DIR=/db
      - SLEEP_TIME=4h
    volumes:
      # use secrets ?
      - $VOLUME_DIR/libation/config:/config
      - $VOLUME_DIR/libation/db:/db
      - $VOLUME_DIR/audiobookshelf/audiobooks/jacobfg:/data
      - $VOLUME_DIR/libation/logs:/logs
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=false"